#!/bin/sh
#-
# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2026 Jeremy McMillan
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

#
# rpi5-bootimg -- rebuild the boot image a Raspberry Pi 5 loads its kernel
# from.
#
# On a Pi 5 booted by rpiboot(8) the VPU firmware, not the loader, reads the
# SD card: config.txt names rpiboot.bin as the "kernel" and a small UFS image
# as the "initramfs", and rpiboot loads the FreeBSD kernel out of that image.
# So after every kernel change the image on the FAT partition has to be
# regenerated from /boot, which is what this does.  See rpi5-bootimg(8).
#

set -e

PROG=${0##*/}

ROOT=/
BOOTDIR=/boot/efi
SWITCH_CONFIG=
DRYRUN=
QUIET=
TRIGGER=
IMAGE=boot.ufs
INITRD_ADDR=0x30000000

# Everything the firmware must load has to fit between INITRD_ADDR and the
# end of the first /memory region; see stand/arm64/rpiboot/copy.c.
MAX_BYTES=$((244 * 1024 * 1024))

usage()
{
	echo "usage: ${PROG} [-cnqt] [-b bootdir] [-r root]" >&2
	exit 64
}

say()
{
	[ -n "${QUIET}" ] || echo "${PROG}: $*"
}

die()
{
	echo "${PROG}: $*" >&2
	exit 1
}

while getopts b:cnqr:t opt; do
	case ${opt} in
	b)	BOOTDIR=${OPTARG} ;;
	c)	SWITCH_CONFIG=1 ;;
	n)	DRYRUN=1 ;;
	q)	QUIET=1 ;;
	r)	ROOT=${OPTARG} ;;
	t)	TRIGGER=1; QUIET=1 ;;
	*)	usage ;;
	esac
done
shift $((OPTIND - 1))
[ $# -eq 0 ] || usage

ROOT=${ROOT%/}
FAT=${ROOT}${BOOTDIR}
CFG=${FAT}/config.txt
KERNEL=${ROOT}/boot/kernel/kernel
LOADERCONF=${ROOT}/boot/loader.conf

#
# Is this system one of ours?  In trigger mode anything else is a silent
# no-op, because the pkg trigger fires on every arm64 system that updates a
# kernel, and only a Pi 5 whose config.txt already boots boot.ufs is ours
# to touch.
#
if [ ! -f "${CFG}" ] || ! grep -q '^[[:space:]]*kernel=rpiboot\.bin' "${CFG}"; then
	[ -n "${TRIGGER}" ] && exit 0
	die "${CFG} does not boot rpiboot.bin; is ${BOOTDIR} mounted?"
fi
if [ -n "${TRIGGER}" ] &&
    ! grep -q "^[[:space:]]*initramfs[[:space:]]\{1,\}${IMAGE}[[:space:]]" "${CFG}"; then
	exit 0
fi

[ -f "${KERNEL}" ] || die "no kernel at ${KERNEL}"

# The root the installed system mounts, from its own fstab.
ROOTDEV=$(awk '$1 !~ /^#/ && $2 == "/" { print $3 ":" $1; exit }' \
    "${ROOT}/etc/fstab" 2>/dev/null)
[ -n "${ROOTDEV}" ] || die "no / entry in ${ROOT}/etc/fstab"

STAGE=$(mktemp -d "${TMPDIR:-/tmp}/${PROG}.XXXXXX")
trap 'rm -rf "${STAGE}"' EXIT
mkdir -p "${STAGE}/tree/boot/kernel"

cp -p "${KERNEL}" "${STAGE}/tree/boot/kernel/kernel"

#
# rpiboot uses the "simp" interpreter, which reads /boot/loader.rc and does
# not process loader.conf.  So translate: every *_load="YES" becomes a load
# of that module, and every plain variable becomes a "set", which the kernel
# then sees in its environment exactly as it would have from loader.conf.
# Lines starting "\" are simp comments.
#
MODULES=
RC=${STAGE}/tree/boot/loader.rc
AUTOBOOT_DELAY=3
{
	echo "\\ Generated by rpi5-bootimg(8) from /boot/loader.conf; do not edit."
	echo "set rpiboot_initrd_root=NO"
	echo "set vfs.root.mountfrom=${ROOTDEV}"
} > "${RC}"

if [ -f "${LOADERCONF}" ]; then
	while IFS= read -r line; do
		case ${line} in
		''|'#'*)
			continue ;;
		esac
		name=${line%%=*}
		value=${line#*=}
		name=$(echo "${name}" | tr -d '[:space:]')
		value=$(echo "${value}" | sed -e 's/[[:space:]]*#.*$//' \
		    -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
		bare=$(echo "${value}" | tr -d '"')
		case ${name} in
		*_load)
			case ${bare} in
			[Yy][Ee][Ss]) MODULES="${MODULES} ${name%_load}" ;;
			esac
			;;
		*_name|*_type|*_flags|*_before|*_after|*_error)
			;;
		autoboot_delay)
			AUTOBOOT_DELAY=${bare}
			;;
		vfs.root.mountfrom|rpiboot_initrd_root)
			say "ignoring ${name} from loader.conf; set from fstab"
			;;
		*)
			# "-": a tunable the loader rejects must not stop
			# the boot, only be reported.
			echo "-set ${name}=${value}" >> "${RC}"
			;;
		esac
	done < "${LOADERCONF}"
fi

echo "load /boot/kernel/kernel" >> "${RC}"
for m in ${MODULES}; do
	found=
	for d in "${ROOT}/boot/kernel" "${ROOT}/boot/modules"; do
		if [ -f "${d}/${m}.ko" ]; then
			sub=${d#"${ROOT}"}
			mkdir -p "${STAGE}/tree${sub}"
			cp -p "${d}/${m}.ko" "${STAGE}/tree${sub}/${m}.ko"
			echo "-load ${sub}/${m}.ko" >> "${RC}"
			found=1
			break
		fi
	done
	[ -n "${found}" ] ||
	    echo "${PROG}: warning: ${m}_load is set but ${m}.ko was not found" >&2
done
echo "autoboot ${AUTOBOOT_DELAY}" >> "${RC}"

makefs -t ffs -B little -o version=2,label=rpi5kern,minfree=0 \
    "${STAGE}/${IMAGE}" "${STAGE}/tree" >/dev/null

size=$(stat -f %z "${STAGE}/${IMAGE}")
[ "${size}" -le "${MAX_BYTES}" ] ||
    die "boot image is ${size} bytes, more than the ${MAX_BYTES} that fit" \
	"above ${INITRD_ADDR}; load fewer modules from loader.conf"

if [ -n "${DRYRUN}" ]; then
	say "would install a ${size}-byte ${IMAGE} into ${FAT}:"
	[ -n "${QUIET}" ] || sed 's/^/	/' "${RC}"
	exit 0
fi

# The old image is about to be freed, so it counts towards the room there is.
avail=$(($(df -k "${FAT}" | awk 'NR == 2 { print $4 }') * 1024))
if [ -f "${FAT}/${IMAGE}.old" ]; then
	avail=$((avail + $(stat -f %z "${FAT}/${IMAGE}.old")))
fi
[ "${size}" -le "${avail}" ] ||
    die "not enough room on ${FAT} for a ${size}-byte ${IMAGE}"

#
# Keep the previous image as .old, so a kernel that does not boot can be
# recovered from any machine that can edit config.txt on the FAT partition.
#
rm -f "${FAT}/${IMAGE}.old"
cp "${STAGE}/${IMAGE}" "${FAT}/${IMAGE}.new"
sync
if [ -f "${FAT}/${IMAGE}" ]; then
	mv "${FAT}/${IMAGE}" "${FAT}/${IMAGE}.old"
fi
mv "${FAT}/${IMAGE}.new" "${FAT}/${IMAGE}"
sync

if [ -n "${SWITCH_CONFIG}" ]; then
	if grep -q '^[[:space:]]*initramfs[[:space:]]' "${CFG}"; then
		sed -E "s|^([[:space:]]*initramfs[[:space:]]+)[^[:space:]]+|\\1${IMAGE}|" \
		    "${CFG}" > "${STAGE}/config.txt"
	else
		{ cat "${CFG}"; echo "[all]"; \
		    echo "initramfs ${IMAGE} ${INITRD_ADDR}"; } > "${STAGE}/config.txt"
	fi
	cp "${STAGE}/config.txt" "${CFG}"
	sync
	say "config.txt now boots ${IMAGE}"
fi

say "installed ${IMAGE} (${size} bytes, root ${ROOTDEV}) in ${FAT}"
